name: "Check pull request"

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Setup environment
        run: cp .env.example .env
      - name: Lint code
        run: pnpm run lint
      - name: Run tests
        run: pnpm run test
      - name: Check coverage
        run: pnpm run coverage
      - name: Build
        run: pnpm run build
